version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
      - "8084:8084"
    volumes:
      - ./:/app
    command: air
    environment:
      - AIR=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - "3200:5173"
    volumes:
      - ./frontend:/app